### PR TITLE
Add hello sqrt(2) program as example for an dynamically linked QNX program

### PR DESCRIPTION
**Pull request by danielmoos**
This adds a new example QNX program which is dynamically linked. The program calculates sqrt(2) via 1/sin(arctan(1)) because the compiler optimizes the direct call sqrt(2) away.

In the [PR#832](https://github.com/qilingframework/qiling/pull/832) support for dynamically linked QNX programs will be added to Qiling.

### CODE REVIEW

**Comment by xwings** [comment]
hi, 

please move the src file to examples/src

**Comment by danielmoos** [comment]
Hi,

I moved the src file to qiling/examples/src/qnx/.

Is there any information about the origin of the libc.so.3 under arm_qnx/lib/? It sends a message of the form:
msg_sys_conf(GET, STR, 12)
while the libc.so.3 from the [qnx650 repo](https://github.com/ezdevelop/qnx650/) sends a
msg_sys_conf(GET, STR, 200)
and OpenQNX defines the symbol CS_LIBPATH as 200.

**Comment by xwings** [comment]
maybe we can maintian two version ?
i will merge this first

**Comment by xwings** [comment]
I added both @madprogrammer  and @danielmoos  into the Contributors list :)

**Comment by danielmoos** [comment]
> I added both @madprogrammer and @danielmoos into the Contributors list :)

Thanks :)

I've used the weekend for some investigation and figured out, that the libc.so.3 in arm_qnx/lib/ was taken from QNX 6.6. The libm.so.2 in this PR is from QNX 6.5 and appearently it is not a good idea to mix libraries from different QNX versions. I've created a new [PR #12](https://github.com/qilingframework/rootfs/pull/12) to update the libm.so.2 to QNX 6.6

**Pull request merged**
